# Generated by Django 5.2.15 on 2026-07-03 13:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short introduction shown next to the picture.', verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='picture',
            field=models.ForeignKey(blank=True, help_text='Profile photo shown in the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='picture'),
        ),
    ]
