# Generated by Django 5.2.15 on 2026-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepage_body_homepage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(blank=True, help_text="Name displayed in the hero section (the page title stays 'Home').", max_length=255, verbose_name='name'),
        ),
    ]
