# Generated by Django 5.2.15 on 2026-07-03 21:42

import json

import wagtail.fields
from django.db import migrations


def wrap_richtext_in_stream(apps, schema_editor):
    """Wrap legacy rich text HTML into a single rich_text stream block.

    Runs while the column is still text, before AlterField converts it to
    JSON, so the cast to jsonb finds valid JSON in every row.
    """
    BlogPostPage = apps.get_model("blog", "BlogPostPage")
    for post in BlogPostPage.objects.all().iterator():
        raw = post.body or ""
        try:
            json.loads(raw)
            continue  # already stream data
        except (TypeError, ValueError):
            pass
        stream = [{"type": "rich_text", "value": raw}] if raw.strip() else []
        post.body = json.dumps(stream)
        post.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(wrap_richtext_in_stream, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('table', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'blockquote', 'code', 'superscript', 'subscript', 'strikethrough']}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('django', 'Django/Jinja2'), ('docker', 'Dockerfile'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('markup', 'HTML'), ('python', 'Python'), ('sql', 'SQL'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'code'}), 4: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}),
        ),
    ]
